### ISSUE TITLE
Error in schematic

### ISSUE THREAD

**Issue by John7746** [NiceCircuits/modules_from_china#1]
CH340G_D-SUN-V3.0_schematic.png

I think diodes D1 and D2 should connect directly and only to CON2 PIN 3, and not to Vcc on pin 16 on U1. The Two diodes create a potential drop roughly giving just above 3v3, so that should be connected to CON2 PIN 3. Then the jumper connector that is placed on CON2 can select whether to connect 5V on CON2 PIN1 to CON2 PIN2, or in the other jumper position, CON2 PIN3 will be connected to CON2 PIN2. This provides the user with a voltage selection to Vcc.

On this schematic, D1 and D2 connecting to Vcc directly does not make sense when considering the purpose of the jumper used with CON2.

Kind regards,
John

**Comment by NiceCircuits** [comment]
This connection is OK, I just checked. If it's proper datasheet it also makes sense: "When using 3.3V
power voltage, connects V3 with VCC, and input 3.3V power voltage."
https://cdn.sparkfun.com/datasheets/Dev/Arduino/Other/CH340DS1.PDF
